### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by bakintunde** [TemenosDS/ScriptsEtcForPreSalesVM#1]
Hi,
These links don't work.

http://cloud-ivy.temenosgroup.com/build/utp/UTP_Build_Latest.7z
http://p2.oams.com/dist/latest/master/

**Comment by vorburger** [comment]
@bakintunde these links were to TEMENOS internal software distribution sites.. if you find what is in this old demo repo of mine back from the day when I worked at TEMENOS (I do not anymore FYI) useful, then just ignore these links and instead use the respective end-user software packages you got from TEMENOS.

**Comment by vorburger** [comment]
I've removed the (already commented out man...) links in https://github.com/vorburger/ScriptsEtcForPreSalesVM/commit/a374f609722a45b84534e9a591480346486e6296, so closing this - hope this helps.

**Comment by bakintunde** [comment]
@vorburger Thanks.
