### ISSUE TITLE
docker build fails with the following error: Unable to locate package language-pack-en

### ISSUE THREAD

**Issue by Kusmarius** [TemenosDS/ScriptsEtcForPreSalesVM#2]
Step 6/41 : RUN apt-get install -y --no-install-recommends language-pack-en &&     locale-gen en_US &&     update-locale LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 &&     mkdir /etc/container_environment &&     echo -n en_US.UTF-8 > /etc/container_environment/LANG &&     echo -n en_US.UTF-8 > /etc/container_environment/LC_CTYPE

Results in:

E: Unable to locate package language-pack-en

**Comment by vorburger** [comment]
Hello @Kusmarius. Thank you for your interest in this repository. 

Unfortunately I'm not able to maintain this project anymore, or offer any support for it. I will therefore, respectfully, close this issue.

I'll also use this opportunity to ARCHIVE this project on GitHub, which makes it read-only (no more new Issues or Pull Requests).

You are, of course, free to "fork" this git repository and fix any problems you like to yourself.

Hope this makes sense and you understand.

All the best.
